### ISSUE TITLE
Lucide 1.0 - Defining Scope and Features

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#1687]
# Defining Lucide 1.0

## Summary

Lucide is almost reaching the 300 in the minor version number and it’s good to start thinking about version 1.0 and start working to this goal.

Looking at some issues we have open on Github we can define 1.0. If combine the relevant issues in one list we can split it up into 3 sections: “icons”, “Community” and “packages”.

## Subjects & issues

**Icons**

- [ ]  Complete the list of icons of feather icons issues **[#119](https://github.com/lucide-icons/lucide/issues/119)**
- [ ]  Fix icon size designs [#1192](https://github.com/lucide-icons/lucide/issues/1192)
- [ ]  Fix guideline violations
    - Remove Brand Icons **[#94](https://github.com/lucide-icons/lucide/issues/94)**
    - Rename icons that end with -2, etc.
    - Rename icons that do have not a generic name.
    - Make a list of icons that we are not happy with.
- [ ] Flatting SVG paths?
    - Only for shipped packages
    - This makes using opacity better
    - Needs research on how to deal with path shapes like “circle, rect, etc.”
- [ ]  Remove brand icons #94
    - [ ]  Will be executed on v1
    - [ ]  Add warning for all packages.

******Community******

- [x]  New website **#649**
    - [x]  Icon Categories on website **[#669](https://github.com/lucide-icons/lucide/issues/669)**
- [ ]  Improve documentation
    - [x]  Basics documentation section **#1521**
    - [ ]  Migration guide Feather → Lucide
    - [ ]  Advanced documentation section
    - [ ]  Figma plugin showcase
- [ ]  Add a Contributors License Agreement
- [x]  Conventions for naming icons **#112**
- [ ]  Second library for superfluous icons
    - Some proposed icons are nicely designed but have unknown usecase.
    - Discussions in https://github.com/lucide-icons/lucide/issues/1607

****************Packages****************

- [x]  Add aliases support
- [x]  API of `lucide-angular`must be the same as other lucide packages
- [x]  Fix the font building
- [ ]  Make packages stable as possible
    - [ ]  Solve Svelte slow import issue [#1284](https://github.com/lucide-icons/lucide/issues/1284)
    - [ ]  Svelte: Module not found https://github.com/lucide-icons/lucide/issues/1572
    - [ ]  Slow dynamic imports NextJS https://github.com/lucide-icons/lucide/issues/1576
- [ ]  Publishing package under `@lucide/{packageName}`
    - [ ]  lucide-vue-next → `@lucide/vue`
        - no vue 2 support (will be EOF end of this year)
- [ ]  Create release workflow [**#1550**](https://github.com/lucide-icons/lucide/issues/1550)
    - [ ]  Choose a better way to release semantic
- [ ]  `absoluteStrokeWidth`  ⇒ `vector-effect: non-scaling-stroke`
- [ ]  Dynamic imports support for all packages
    - [x]  React package
    - [ ]  Vue package
    - [ ]  Svelte Package
    - [ ]  Solid Package
    - [ ]  Preact Package
    - [ ]  Angular package?

### Icons

We have added so many new icons in the past year. We now have more than 1300 icons, that’s the crazy number if you compare it with where we started with 287 icons. Thank you to all contributors who contributed all those icons, We should continue with adding more. 

But for 1.0 we can’t determine which icons we should have included in our library, it will always be an ongoing process. However, we started issue **[#119](https://github.com/lucide-icons/lucide/issues/119)** almost from the beginning. It would be a nice achievement if we could say we have added all requested icons from the feather project. We have still 15 icons to go!

If we look at the whole library, we still have some icons that are not well-named. Some are not generic and some are a bit weirdly named. Also, we want to stop naming icons with a `-2` suffix. Brand icons will be removed on v1.0.

We want to make it easier to work with Lucide icons by exploring the idea of flattening SVGs. This will make it easier to use alpha color values with Lucide icons like `rgba`, `hsla` etc. Currently, it's making overlapping icons visible. This also can make the library a bit smaller and more performant, since machines only need to draw an SVG path one time.

### Community

Some call it our marketing website, our “front of site”. But it’s more of that. It’s a tool to find your icons, a tool to adjust icons, and it’s a book of documentation on how to use our libraries.

The last year we improved it a lot. With the launch of the new website, we have created something we can continue for the next years. And we are happy that we switched to Vitepress which is updated frequently. 

But we are not done yet, we still need to improve our documentation. We have already written a “basics” section, which helps to get started. But we also want to write more “in-depth” articles about using Lucide icons. Some topic ideas: “Accessibility”, “Global styling”, “Animations”.

We should highlight the Figma plugin more. The Lucide Figma plugin is a great addition to the Lucide ecosystem. It also meets new designers to contribute to Lucide.

We also have ideas about a second icon library containing icons without known use cases. Before we merge new icons in the library, we require icons to have a valid use case. Otherwise, we will end up with icons people will never use. But unfortunately, we reject icon proposals now and then, some icon designs are beautifully made. So we want to explore the idea of a second library that contains these “rejected” icons. We will research the use of these icons and consider adding them to the main library. 

### Packages

We want to make all packages as stable as possible, but we still have some issues with certain frameworks. We need to solve these issues before going to v1.

For the React package, we added some experimental features like [dynamicImports](https://lucide.dev/guide/packages/lucide-react#with-dynamic-imports) and [JS Docs](https://github.com/lucide-icons/lucide/pull/1424). These features are well adopted and should be added to all other packages as well.

Packages should be released under the @lucide organization. This will make it more clear that packages are official Lucide packages, and we don’t have any name conflicts when we want to publish new packages.

But it requires devs to change the package name. Not sure if NPM has something to migrate from `lucide-react` to `@lucide/react` for example. But we should make this change on Lucide 1.0

## Feedback

We encourage the community to provide feedback on this RFC. Your input is valuable and will help us shape the direction of Lucide 1.0. Please feel free to share your thoughts, suggestions, concerns, or any other feedback you may have.

To provide feedback, you can:

- Leave a comment on this GitHub issue
- Join our community Discord server and participate in the #lucide-1.0 channel
- Reach out to the Lucide team directly via email at [team@lucide.dev](mailto:team@lucide.dev)

We appreciate your involvement and look forward to hearing from you!

## Participate

We welcome and encourage everyone to participate in the development and improvement of Lucide 1.0. Your contributions, feedback, and ideas are vital to shaping the future of Lucide.

Feel free to help on those open issues we linked in the “Subjects & issues” section. For new features, make sure you post a comment on the issue and share your ideas before you start working on it.

We will label issues with `Version 1` to easily filter on these.

Thank you to all the people who already contributed to Lucide. Let's create an amazing icon library for developers worldwide!

**Comment by zaaakher** [comment]
Wonderful 👍 

Here are a few suggestions that just came to mind:

## Lucide History
#### Something like `lucide-history` or `lucide-archive`
Putting all the removed icons (throughout lucide history) into a separate package/repo
- This will simulate a "backward-compatibility" experience for developers using old deprecated/removed icons
- it will also comfort any designer who previously contributed new icons to Lucide and doesn't want to see their work disappear into the abyss and instead they can still use it via that package. 
- it could streamline the process of bringing back a removed icon just in case minds changed about a certain icon.

It's true that I can just install an older version of lucide to access a removed icon, but that would have two problems:
- I wouldn't know which version the removed icon was last published in (I would have to do some deep digging since the old 
 removed icons won't be in the website)
- I can't use the latest version (let's say v1.0) to access new fresh icons, while also using an older version to access that one or two removed icon I need. 

## Lucide AI
#### an AI that generates new lucide icons
Since the design guidelines/standards are clear and concise, we can perhaps feed it to an AI that would assist generating new icons based on a prompt. 
- This would make it easier for non-designers and people with no vector graphics editor program to easily suggest icons with an actual SVG starting point to help the maintainers. 
- Depending on how good the result of the ai is, the maintainers may do some additional touch-up or just approve and merge without having to touch the svg (if the AI result was perfect)
- Having this human-ai interaction might help refine the design guidelines & standards based on mistakes and misinterpretations of the AI generator.

## NPM Package names
#### Getting the `@lucide` npm handle

It would be great if the npm packages were named like:
`@lucide/core`
`@lucide/react`
`@lucide/vue`
... etc

As I'm writing this, I noticed that `@lucide` npm handle is taken by an empty unused [organization](https://www.npmjs.com/org/lucide). In this case I suggest the maintainers to file an [npm name dispute form](https://support.github.com/contact/npm-name-disputes). Although it's not garuanteed npm would release that handle to us, but inshallah they will, since this is growing and beautiful open-source project that's well-maintained ✨


Another teeny tiny suggestion is to remove "a fork of Feather Icons" from this project bio since it's already mentioned in the README. (and we have about a thousand more icons than feather-icons). But that's just my opinion, 😁

**Comment by karsa-mistmere** [comment]
@zaaakher: 

> `lucide-history`

To be truly backwards compatible this would pretty much have to be an extra package per framework, which is a burden we're not really willing to take.
Other than this technical issue, icons queued for removal are brand icons only and this is due to copyright and brand guideline violations, so still keeping these icons around in any official format would not resolve this issue.
As Eric has mentioned, we're looking into building a new Lucide ecosystem where third party icons can be more fluidly added; people wishing to knowingly violate brand icon guidelines or copyrights will be able to piggyback this system, but we will no longer support these icons under the Lucide flag in any way.

> Lucide AI

Fun idea, but I'd put this in the v1.1 or even v2 milestone idea box (or we'll never manage to finally release v1). 😄

> The `@lucide` npm namespace

This is part of our v1 RFC, it's in Eric's checklist under Packages. To my best knowledge, the handle was also reserved by him. 🙂

**Comment by zaaakher** [comment]
> it's in Eric's checklist under Packages

Oops I totally missed that, I came in guns blazin' with thoughts I didn't even read the full text 😅

>To be truly backwards compatible this would pretty much have to be an extra package per framework, which is a burden we're not really willing to take.

Oh ok in that case it's definitely not worth it since it's mostly for very rare edge cases.

> Fun idea, but I'd put this in the v1.1 or even v2 milestone idea box (or we'll never manage to finally release v1). 😄

Agree, I don't think it should be anchored to any version, just an experimental path to explore until its mature enough to be released.


I'm excited about the future of this project and looking forward to collaborating with you all when possible. 👍🌹

**Comment by josephclaytonhansen** [comment]
Should lucide labs be added to this list? Also, a web icon viewer for labs would be awesome 👀

**Comment by ghost** [comment]
Hello, is there any interest in a desktop package? 
For instance a WPF library to turn Lucide icons into ImageSources, Bitmaps, etc. What I have in mind could be used to modify icons details dynamically (size color etc) based on application logic without multiple resource files.

**Comment by ericfennis** [comment]
@Phexyaa I think this is not something we should discuss for the goal of V1. I recommend creating a [discussion](https://github.com/lucide-icons/lucide/discussions) so you can evaluate interests from the community.

**Comment by chessurisme** [comment]
It is nice if #119 is getting an update.

**Comment by SimonDatapas** [comment]
Is there any expectations, planning,  insights on a timeline or a due date for the v1 release?

**Comment by tryoxiss** [comment]
I would highly suggest not implementing a CLA. To me and many people in the open source community, they are a huge red flag because they considerably increase difficulty of making contributions, often allow the organisation to relicence the software to make it not open source anymore, and there is VERY little reason to have one if you don't intend to use that power.

Additionally, it indicates that the maintainers don't consider the licence good enough to protect from legal troubles, and if even the maintainers are indicating that how should a user feel safe that the licence would hold up for them?

All of the benefits (with none of the problems of trust/red flags) can be achived with a simple [Ddeveloper Certificate or Origin (DCO)](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin), where the contributor affirms (in the PR) that (1) they hold the copyright to the contribution in question and (2) licence it as the rest of the project is. If its good enough for linux, its good enough for every project.

If you want more depth there is [an article on why open source projects probably shouldn't add a CLA](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/) (plus many other articles if you just google).

(Obligitory I am not a lawyer)

**Comment by briz123** [comment]
Would it be helpful to update the contributing guide to include the PR conventions? Also, I mentioned this elsewhere but in that same stroke we could add information about/linking to Lucide Studio? My first time opening a PR in lucide I didn't know about the conventions since it wasn't mentioned anywhere.

**Comment by Wolfr** [comment]
Seemingly I am reacting to an old topic but anyhow... here's my two cents on some of the topics. This is coming from a place of experience maintaining our own icon kit at https://icons.obra.studio/ (recently also MIT licensed)

## Missing icons

First of all, the Feather icon requests - if they were not handled in 5 years, they will not be handled now. Imo I would just ignore that topic and close it due to too old. If something new is needed, it will surface.

#3289 # Optical size fixes

This is an ongoing thing that you could fix over time.

A user of Lucide icons wouldn't expect the optical size of an icon to change too much after using it. I would consider these a bug fix that can be handled over time in a patch version of 1.X.

If they find the change too big they can always lock their version.

If the community feels it's necessary, you could grab icons from Obra Icons or Phosphor Icons (which are fully MIT-licensed) and drop them into Lucide for an easy fix (possibly rework to Lucide standards)

A cursory look reveals a rather limited list of icons to be handled... imo you don't _need_ to fix those for 1.0 and optical improvements could be part of a 1.X release.

## Flatten the SVG icons

I don't know about this, people can always use opacity on the whole SVG object? I don't super understand this issue really. The discussion centers around being able to use rgba() and lines overlapping.

I haven't really encountered this problem within Obra Icons because I do flatten them in some cases (e.g. in the direct copy from website logic).

In general I believe it's nice to keep the code editable and clean and provide a version that has the `rect` `circle` etc. SVG parts in the code. I think that's actually faster to render in SVG than an arbitrary path with a lot of instructions. 

## Brand icons

The UX of using a separate package is annoying, and I would rather just put straight up logo SVG inside of the package, albeit adjusted to the expected bounding box size like I do with Obra Icons.

A separate package could be considered with brand icons, I also considered the same for Obra Icons.

If you do not modify the logo whatever and just put a vector of the X logo (Apple logo, whatever logo) I think it falls under a fair use policy. Obviously disclaimer I am not a lawyer. 

Changing the logos to follow the style of Lucide feels like weird work to me; a logo is a logo and needs to be respected as such.

The main use case for this is likely linking to social media accounts (e.g. in the footer of a website).

I think it's good to have common brand icons of social media just like I do in Obra Icons.

## 2nd library for the icons without a clear use case

I think this will lead to too much discussion. Main maintainers should use common sense to add or reject icons to the library. A second package will cause confusion.

**Comment by ericfennis** [comment]
For discussion about Lucide v1, Go to the [Lucide V1 Discussion Category](https://github.com/lucide-icons/lucide/discussions/categories/lucide-v1)
